const GETLIST = 'GETLIST'
const FORUM_SUMMARY = 'FORUM_SUMMARY'         // 论坛简介
const FORUM_LIST = 'FORUM_LIST'               // 论坛列表
const FORUM_ACTIVITY_LIST = 'FORUM_ACTIVITY_LIST'               // 论坛活动贴列表
const FORUM_DETAIL = 'FORUM_DETAIL'           // 论坛详情
const FORUM_DETAIL_REPLAYS = 'FORUM_DETAIL_REPLAYS'           // 论坛详情
const GETHOMELIST = 'GETHOMELIST'             // 获取论坛首页列表
const GETUSERDETAIL = 'GETUSERDETAIL'         // 获取用户信息
const GETATMELIST = 'GETATMELIST'             // 获取@我列表
const GETREPLYMELIST = 'GETREPLYMELIST'       // 获取回复我列表
const GETREPLIEDLIST = 'GETREPLIEDLIST'       // 获取我回复的列表
const GETFAVORMELIST = 'GETFAVORMELIST'       // 获取赞了我的列表
const GETFAVOREDLIST = 'GETFAVOREDLIST'       // 获取我赞了的列表
const GETFAVORLIST = 'GETFAVORLIST'           // 获取点赞列表
const GETMYPOSTLIST = 'GETMYPOSTLIST'         // 获取我的帖子列表
const GETVOTERLIST = 'GETVOTERLIST'           // 获取投票人列表
const GETCLOCKLIST = 'GETCLOCKLIST'           // 获取打卡列表
const DELETE_POST = 'DELETE_POST'             // 删除帖子
const DELETE_REPLY = 'DELETE_REPLY'           // 删除回复

const FORUM_VOTE_AGREE = 'FORUM_VOTE_AGREE'       // 投票同意
const FORUM_VOTE_DISAGREE = 'FORUM_VOTE_DISAGREE' // 投票不同意
const FORUM_PAY_TO_JOIN = 'FORUM_PAY_TO_JOIN'     // 支付参加活动
const FORUM_MORE_REPLY = 'FORUM_MORE_REPLY'       // 获取更多评论
const FORUM_SWITCH_LIKE_OR_NOT = 'FORUM_SWITCH_LIKE_OR_NOT' // 点赞或取消

export {
  GETLIST,
  FORUM_SUMMARY,
  FORUM_LIST,
  FORUM_ACTIVITY_LIST,
  FORUM_DETAIL,
  FORUM_DETAIL_REPLAYS,
  GETHOMELIST,
  GETUSERDETAIL,
  GETATMELIST,
  GETREPLYMELIST,
  GETREPLIEDLIST,
  GETFAVORMELIST,
  GETFAVOREDLIST,
  GETFAVORLIST,
  GETMYPOSTLIST,
  GETVOTERLIST,
  GETCLOCKLIST,
  DELETE_POST,
  DELETE_REPLY,
  FORUM_VOTE_AGREE,
  FORUM_VOTE_DISAGREE,
  FORUM_PAY_TO_JOIN,
  FORUM_MORE_REPLY,
  FORUM_SWITCH_LIKE_OR_NOT
}
